"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useAuth } from "@clerk/nextjs";
import { getTailoredResume } from "../../lib/api";
import { Spinner, useToast } from "../../components/ui";

export default function TailoredResumePage() {
  const { getToken } = useAuth();
  const { jobId } = useParams();
  const router = useRouter();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const { showToast, ToastComponent } = useToast();

  useEffect(() => {
    async function load() {
      try {
        const token = await getToken();
        if (!token) return;
        const res = await getTailoredResume(token, jobId);
        setData(res);
      } catch (err) {
        showToast("Tailored resume not found for this job. Ensure you clicked 'Tailor Resume' in the Pipeline.", "error");
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [jobId, getToken]);

  const handleDownload = () => {
    const blob = new Blob([data?.latex || ""], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tailored_${jobId}.tex`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(data?.latex || "");
    showToast("Tailored LaTeX copied!");
  };

  if (loading) return <div className="flex justify-center py-20"><Spinner /></div>;

  return (
    <div className="max-w-4xl mx-auto h-[calc(100vh-140px)] flex flex-col">
      <div className="flex justify-between items-end mb-6">
        <div>
          <button 
            onClick={() => router.back()}
            className="text-xs font-bold text-[#5a5c72] uppercase tracking-widest hover:text-white transition-colors mb-4 block"
          >
            ← Back to Pipeline
          </button>
          <h1 className="text-3xl font-bold tracking-tight mb-2">Tailored Resume</h1>
          <p className="text-[#8a8ca0] text-sm italic">Optimized version for Job ID: {jobId}</p>
        </div>
        {!data ? null : (
          <div className="flex gap-3">
            <button
              onClick={handleDownload}
              className="px-6 py-2 bg-white/5 border border-white/10 text-white font-bold rounded-xl hover:bg-white/10 transition-all text-xs"
            >
              Download .tex
            </button>
            <button
              onClick={handleCopy}
              className="px-6 py-2 bg-green-600 text-white font-bold rounded-xl shadow-lg shadow-green-600/20 hover:scale-105 transition-all text-xs"
            >
              Copy LaTeX
            </button>
          </div>
        )}
      </div>

      {!data ? (
        <div className="glass-card p-20 text-center border-dashed border-2 border-white/5 bg-black/40">
           <p className="text-[#5a5c72] font-medium">No tailored resume found.</p>
        </div>
      ) : (
        <div className="glass-card flex-1 flex flex-col overflow-hidden border-[#7c5cfc]/20 bg-black/40 shadow-2xl">
          <div className="px-6 py-3 border-b border-[#7c5cfc]/10 bg-[#7c5cfc]/5 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
              <span className="text-[10px] font-black uppercase tracking-widest text-[#7c5cfc]">Optimized LaTeX Output</span>
            </div>
            <span className="text-[10px] font-mono text-[#5a5c72]">tailored_{jobId}.tex</span>
          </div>
          <textarea
            readOnly
            value={data.latex}
            className="flex-1 p-8 bg-transparent text-sm font-mono text-[#d0d3e2] outline-none resize-none selection:bg-[var(--accent)]/30"
            spellCheck="false"
          />
          <div className="px-6 py-3 bg-green-600/5 border-t border-white/5 text-center">
            <p className="text-[9px] font-bold text-green-500 uppercase tracking-[0.2em] opacity-80">Generated by AI • Source Parity Maintained</p>
          </div>
        </div>
      )}
      {ToastComponent}
    </div>
  );
}
